### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by FSund** [RamonUnch/AltDrag#1]
How do you recommend installing this? Just overwriting the existing AltDrag files in AppData/Roaming? Will it work with an existing AltDrag configuration?

**Comment by RamonUnch** [comment]
I recommend removing the old install and then extract the zip in any folder. AppData/Roaming will work.
The old .ini file should work but some options have changed and it is best if you use the latest and review the config for what you want to modify from default.

AltDrag will not modify the registry nor any file outside of AltDrag.ini.

For the moment some options have to be changed with the .ini file (middle click on AltDrag tray icon).

**Comment by RamonUnch** [comment]
From release 1.31 an installer is included.
