### ISSUE TITLE
Can't scroll while dragging file

### ISSUE THREAD

**Issue by kimks3** [RamonUnch/AltDrag#10]
I noticed that versions after 1.29 seem to have issues scrolling when the LMB is down. The scroll wheel does nothing until the button is released, making it impossible to highlight text, drag a file, etc. beyond the current viewport using the wheel.

I think this may be related to a similar issue some versions had where some programs erroneously receive two scroll events when the wheel is turned one notch.

Here's my quick test (Win 7 x64, "scroll inactive" enabled):
V1.29: Works as expected.
V1.30: Scrolls twice per wheel detent in some apps (Chrome, Win7 tray calendar, etc). Also doesn't allow scrolling while LMB is down (ie, can't scroll with wheel while dragging a file)
V1.31: Still doublescrolls. Drag scroll seems to work.
V1.32: Doublescroll fixed but now drag scroll broken.
V1.33: Ditto

Thanks for the work on keeping Altdrag alive.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5790384/hooks.zip)
Try with this hooks.dll in your 1.33 install

**Comment by kimks3** [comment]
> [hooks.zip](https://github.com/RamonUnch/AltDrag/files/5790384/hooks.zip)
> Try with this hooks.dll in your 1.33 install

Sadly no difference on my end. It's possible to scroll OTHER windows, but not the active one in which LMB was depressed.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5790479/hooks.zip)
Try again with this one and if it does not work, try to clear the Windows Blacklist.

**Comment by kimks3** [comment]
Awesome, seems to be working properly with the new dll. Thanks for the quick fix!
