### ISSUE TITLE
AlstSnap chocolatey package waiting for validation

### ISSUE THREAD

**Issue by dmnmsc** [RamonUnch/AltDrag#118]
Hi,

I can't find altsnap in chocolatey. According to this https://community.chocolatey.org/packages/altsnap/1.47#collapsing-right-sidebar some Checks Have Failed or Are Not Yet Complete

We can still install altdrag by chocolatey but we can't install altsnap using chocolatey.

**Comment by RamonUnch** [comment]
Because it is a new package it needs to wait for manual validation.
This will be the case for the few next releases.
If you want to install before the validation you can use:
`> choco install altsnap --version=1.47`
