### ISSUE TITLE
Feature request: When lowering a window, also lose focus so that the lowered window can be immediately re-clicked

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#12]
Take the scenario where you have a larger window on top of a smaller window contained within its footprint. For example, middle-clicking on the title bar (assuming the option for that behavior is enabled) lowers the window, revealing the smaller window. Now click on the larger window in the background and it will remain behind the smaller window (as the former still has the focus but without being in the foreground any longer). You must first change focus (click another window or the desktop) and then you are able to click on the background window, bringing it to the foreground.

Either this is a bug of some sort, or maybe the focus could be lost when a window is lowered to always make any window clickable and "bringable" to the foreground. When I say focus, hopefully focus can be transferred without say maximizing a minimized game (if the last used app was the default target). An alternative would be to give focus to the desktop (if possible) as a "safe" and predictable thing to receive focus in that scenario.

Thanks!

```
Windows 10 20H2
AltDrag 1.32
```

**Comment by RamonUnch** [comment]
An other sensible option would be to transfer the focus to the topmost window when the window that has the focus is lowered.
I will make this modification and let you test and see what you think.

**Comment by RamonUnch** [comment]
Does this one fixes your problem?
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5808476/hooks.zip)
I could not do exactly what I wanted but it seems to be an improvement to me.

**Comment by redactedscribe** [comment]
It seems my choice of window to test (Firefox) wasn't ideal as it still doesn't work. I guess the Firefox window is special somehow. But your fix does work for other windows (I just compared between this dll and 1.32's): windows now lose focus making them easy to click after lowering. 🙂

**Comment by RamonUnch** [comment]
Yes indeed Firefox does not behaves
I am not sure what I can do about it.

**Comment by RamonUnch** [comment]
If you want re-set Firefox on top, you actually can click the title bar.

**Comment by redactedscribe** [comment]
Also middle-clicking is another way and this can be done anywhere in the Firefox window. Maybe one day, left-clicking will work too.

**Comment by RamonUnch** [comment]
I close the issue that is mostly resolved by now. I will still search occasionally for Firefox's special case.

**Comment by redactedscribe** [comment]
Strange. It seems this does not work any longer: a lowered Windows File Explorer isn't able to be brought to the foreground via click. Same problem as original issue, must first focus another window, then click the lowered window again.
