### ISSUE TITLE
Microsoft PowerToys Implementation

### ISSUE THREAD

**Issue by child-duckling** [RamonUnch/AltDrag#13]
Apparently someone is trying to implement this same idea into MS PowerToys and has abandoned the project.
[https://github.com/microsoft/PowerToys/pull/6979#issuecomment-733266923](https://github.com/microsoft/PowerToys/pull/6979#issuecomment-733266923)

**Comment by RamonUnch** [comment]
Very sad that this project stopped.
The truth is that it is very integrated into PowerToys, I never worked on this project and It would take ages for me to understand the logic and to start to be able to write something.

For the moment the only thing I use in PowerToys is the bulk rename utility.
If you want AltDrag to work in together with FancyZones you need to really integrate the program into PowerToys.

**Comment by RamonUnch** [comment]
I will keep this issue pinned and When I will have time to implement a PowerDrag compatible version I will re-open it.

**Comment by RamonUnch** [comment]
Work in progress see issue https://github.com/RamonUnch/AltSnap/issues/97
