### ISSUE TITLE
Bug: MinAlpha=0: Scrolling on windows or the desktop is buggy

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#17]
With `MinAlpha=0`, scrolling to minimum on a File Explorer window causes it to disappear and have no way to be made non-transparent. Scrolling up in the same spot does nothing: the window is gone it seems.

Scrolling to the minimum on the desktop causes it to break. I can't seem to take a screenshot of it but it essentially looks like [this](https://www.voicy.network/Content/Clips/Images/f679a398-1d9e-4be5-a25e-664c4d0184c8.jpg) but much worse (no actual error windows appear, just a lot of visual artifacts of any moved window/thing). At this stage, I have to reboot because the system is a mess.

AltDrag v1.35

**Comment by RamonUnch** [comment]
The minimum will be one from 1.36
It is expected, when you set Alpha to 0 actually Windows disables the window.
The other bug is that the desktop is not blacklisted by default, this will be fixed as well.

**Comment by RamonUnch** [comment]
You should Add 
,Program Manager|Progman
at the end of your Windows blacklist
