### ISSUE TITLE
Feature Request: Roll / collapse windows into their title bar

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#19]
One thing I miss from other similar programs I've used in the past ([WinRoll](https://web.archive.org/web/20160308022342/http://www.palma.com.au/winroll/) / [4t Tray Minimizer](https://www.4t-niagara.com/tray.html)) is being able to shrink a window into only its title bar. I found this quite useful to quickly look behind a window or when I only need to see the title bar, or for example comparing two images (if both windows are on top, you can toggle the "window rolling" and compare both images). Maybe such a feature would be a possibility for AltDrag's mouse actions. This feature is expected to be a little buggy since not all windows manage to collapse into their title bar, e.g. Firefox (but it still does shrink considerably, and restores when "unrolling").

From https://github.com/RamonUnch/AltDrag/issues/7#issuecomment-768831406.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5889954/hooks.zip)
Have a try with this version of Hooks.dll

Alt+Shift+DBLeftClick should Roll/Unroll a window.

Note1: If you snap a rolled window it will not save its previous state (it is normal)
Note2: Maximized window will become focused when unrolling them.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5894393/hooks.zip)
This one should be beter:
ie: if you AltDrag-Snap a rolled window, it will be restored to its initial state instead of the rolled-without memory state.

**Comment by redactedscribe** [comment]
When I said mouse actions, I was hoping it would be implemented as one of the choosable actions left/middle/right/mb4/mb5/scroll.

Ergonomically, I think it would be cool if the window rolling could work with Alt+Scroll Up/Down when over the title bar, that is, if you wish there to be a default combination, on top of methods to perform this action via the mouse actions I just mentioned.

It seems to work fairly reliably at the moment. Something (potentially unavoidable) that I've noticed is that if the AltDrag config is reloaded (disable then enable) and the window was rolled-up (only title bar showing), then it is not possible to restore it. This is a small and rare scenario, and the window can be fixed by dragging/clicking the border.

A nice feature of how it is currently working is: if you roll the window up, then double-click normally on the title bar, the window maximizes. Restoring the window restores it back to its rolled-up state (which I think is convenient). This way you can have numerous rolled-up windows, and maximize them to have a look at them, and restore to look at another rolled-up window.

**Comment by RamonUnch** [comment]
This will be a selectable action as well, I amjust giving you the dev builds because you appear to appreciate and you are a good beta tester.
The AutoRemaximize option has problems, sometime even outside snapping.

It is nor really possible to keep the database when enabling/disabling altdrag because all the memory is lost and this is somewhat the point of enabling/disabling AltDrag

**Comment by RamonUnch** [comment]
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5897647/AltDrag.zip)
Ok, here is the full action.
1) The "Roll/Unroll window" action is available in the list for any button.
2) You can add:
RollWithTBScroll=1
; Roll/Unroll Window when using the Alt+Scroll wheel on its title bar.
in the [Input] section of your .ini file.
3) Now when restoring a Maximized-then-rolled window the window is properly restored.
4) If you roll, then maximize, then roll again a window, it will loose its previous memory and it will be rolled when restoring it and you will have to manually resize it (I donot want to have to remember several entry in mi database for the same window.

**Comment by redactedscribe** [comment]
Some improvements I'd like to suggest:

For `RollWithTBScroll=1`, only allow scroll Up to roll the window, and only allow scroll DOWN to unroll the window. This would be better because mice wheels that are inaccurate can easily and unintentionally send multiple scrolls, leading to the window rolling then unrolling, when for example, the desire is to send 1 action: roll the window. I guess this should be the same behavior whether rolling is done via `RollWithTBScroll` or any button mouse action.

I'm not sure why, but with your previous hook, Windows Terminal was collapsing to only its title bar (desired), but now, only collapses to (undesired):
![2021-01-30_15-01-09](https://user-images.githubusercontent.com/25013746/106356977-0172f300-630c-11eb-9ec4-f19640f7c25b.jpg) - Strange, I just downloaded 1.35 and installed the previous hooks.dll above, and it still collapses like the screenshot. I'm certain it didn't do this before, but I guess something else must be at fault. Other windows seem fine.

Something else regarding Windows Terminal: Normally, my hotkey+scrolling changes transparency when focusing the window (not the title bar), but for WT, it rolls the window, meaning I cannot change the transparency any more.

When a maximized window is rolled up, is it possible that when unrolling it, the window doesn't return from the minimized state? (I see an animation like the window is retuning from minimized). Preferably, the window would simply unroll, just like what happens to non-maximized windows.

**Comment by RamonUnch** [comment]
>When a maximized window is rolled up, is it possible that when unrolling it, the window doesn't return from the minimized state? (I see an animation like the window is retuning from minimized to maximized). Preferably, the window would simply unroll, just like what happens to non-maximized windows.

I would lik it to be possibel unfortunatly it does not work unless minimizing/restoring. Maybe there is an other trick but I dont know.

> Something else regarding Windows Terminal: Normally, my hotkey+scrolling changes transparency when focusing the window (not the title bar), but for WT, it rolls the window, meaning I cannot change the transparency any more.

You mean that before you were doing it in the titlebar? Normally the Transparency action should still be the same. You can always scroll while pointing at the close button, but it becomes a small target. Maybe I can add that if you press Ctrl it will not roll on the titlebar but performe the scroll action instead.

>Strange, I just downloaded 1.35 and installed the previous hooks.dll above, and it still collapses like the screenshot. I'm certain it didn't do this before, but I guess something else must be at fault. Other windows seem fine.

I did not change the way windows were rolled, but maybe

> For RollWithTBScroll=1, only allow scroll Up to roll the window, and only allow scroll DOWN to unroll the window. This would be better because mice wheels that are inaccurate can easily and unintentionally send multiple scrolls, leading to the window rolling then unrolling, when the desire is to send 1 action: for example, roll the window. I guess this should be the same behavior whether rolling is done via RollWithTBScroll or any button mouse action.

You are right, it will be beter.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5898025/hooks.zip)
Use Ctrl to prevent Roll on scroll on titlebar (ie Scroll action has priority).
>For RollWithTBScroll=1, only allow scroll Up to roll the window, and only allow scroll DOWN to unroll the window. 
DONE

**Comment by redactedscribe** [comment]
> You mean that before you were doing it in the titlebar? Normally the Transparency action should still be the same. You can always scroll while pointing at the close button, but it becomes a small target. Maybe I can add that if you press Ctrl it will not roll on the titlebar but performe the scroll action instead.

I am fine with the title bar only allowing rolling, I don't think it needs a way to override it to do transparency / whatever action someone has set.

What I was trying to say is: there is no way to make Windows Terminal transparent any more. No matter where my mouse cursor is positioned, title bar or inside the window area, hotkey+scroll only does win rolling now.

> DONE

Works great!

**Comment by redactedscribe** [comment]
Could the action Roll/Unroll be added as a selectable mouse action for "Scroll wheel"?

**Comment by RamonUnch** [comment]
>What I was trying to say is: there is no way to make Windows Terminal transparent any more. No matter where my mouse cursor is positioned, title bar or inside the window area, hotkey+scroll only does win rolling now.
>Also, setting the "scroll wheel" to a different action, for example "Maximize window", hotkey+scrolling on Windows Terminal still only does rolling.


This is because Window terminalidentifies itself as a big title bar so AltDrag always beleave that you are pointing to the titlebar. T'hat is where comes the advantage of Ctrl.

>Could the action Roll/Unroll be added as a selectable mouse action for "Scroll wheel"?

I thought I had done it, bit i forgot. Here is the fix.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5898297/AltDrag.zip)

**Comment by redactedscribe** [comment]
> This is because Window terminalidentifies itself as a big title bar so AltDrag always thinks that you are pointing to the titlebar. That is where comes the advantage of Ctrl.
Ah, makes sense.

> I thought I had done it, but I forgot. Here is the fix.
Works great.

**Comment by RamonUnch** [comment]
this will be in the next release, coming soon, hopefully
