### ISSUE TITLE
Disable mouse change to hand when dragging

### ISSUE THREAD

**Issue by icyhoty2k** [RamonUnch/AltDrag#2]
Please provide an option to disable change of mouse pointer to a hand when dragging

**Comment by RamonUnch** [comment]
You mean only the Hand when dragging or all other cursor changes as well?
It will be easy anyway

**Comment by RamonUnch** [comment]
[AltDrag1.32wip_bin.zip](https://github.com/RamonUnch/AltDrag/files/5680519/AltDrag1.32wip_bin.zip)

Try this, 
You will have to modify AltDrag.ini and set UseCursor=2 in the [Advanced] section
It will be in next releases as well.

**Comment by icyhoty2k** [comment]
Thanks :)
