### ISSUE TITLE
Feature Request: Implement a test window to help with configuring and visualizing AltDrag settings

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#20]
AltDrag could implement a test window, but one that draws the invisible areas (center vs resizing areas), and could let you define the values via UI vs config. It would also be useful for configuring AltDrag's other features because this test window would be known to work correctly, e.g. vs Firefox / Electron apps which can behave oddly.

From https://github.com/RamonUnch/AltDrag/issues/7#issuecomment-768831406.

**Comment by RamonUnch** [comment]
Next release will add the Advanced tab with more options but not yet this test window.

**Comment by RamonUnch** [comment]
Here is a version with a test window, that can be opened in the Advanced tab.
It will be included in the next test release.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6137047/AltDrag.zip)
![image](https://user-images.githubusercontent.com/74856804/111075569-868f2180-84e0-11eb-9fa7-64fa52505993.png)

**Comment by RamonUnch** [comment]
present in AltDrag 1.40
