### ISSUE TITLE
Some fullscreen windows do not move

### ISSUE THREAD

**Issue by bigcrush** [RamonUnch/AltDrag#21]
I move windows between monitor and TV in linux. Dimensions of those are different but linux keeps windows fullscreen while moving between devices. In win7 "Firefox" and "Windows Media Player" (std on win7) in fullscreen mode do not move even on a single device. At the same time Explorer window and "mpv player" does move (between devices, but dimensions do not fit into device).

Is it a bug of AltDrag or win7 or Apps?

**Comment by RamonUnch** [comment]
I do not fully understand your problem, do you mean that some windows cannot be moved at all once in fullscreen?

Otheriwse by default when you move a fullscreen window with altdrag the window should be restored, then when you bring it to another monitor you have to remaximize it manually (snap on top or doubleclick) unless you use AutoRemaximize=1 in [Advanced] section of AltDrag.ini

OK, Now I think I understad, when you said "fullscreen" I was thinking "Maximized" but actually they are not the same...
A FullScreen window in general is a videogame and I try to ignore it. So if AltDrag sees a window that has no caption and no system menu and has the size of the monitor then it should not be movable.
So the fact that you can move MPV window when in fullscreen is somewhat a bug.

It should be possible however to detect Fullscreen windows and allow to move them and resize them to the monitor you move them to. I will see what I can do, however it would potentially interact with other fullscreen windows that you would not want to interact with.

**Comment by bigcrush** [comment]
Yes, I meant exactly that, as you described. Maybe it is possible to config that some windows can be moved even in Fullscreen mode. I believe such a list will be short. Nevertheless thank you very much for maintaining very useful app.

**Comment by RamonUnch** [comment]
I just checked for Firefox's full screen window and actually it is not ignored by AltDrag by default (you can see it because the cursor changes), however its window does not respond to resizing when in full screen mode, So i think it will not be possible with this program.

In general, if the cursor changes when you try to move resize a window it means that AltDrag is really trying and if the window does not move it means that the window can not be resized (does not respond to the resize commands).

Some full screen window are movable though. I will make sure that they are automatically resized to monitor like maximized windows with AutoRemaximize option.
I will see on other programs if a whitelist is necessary, or just an option.
A version will be posted here when ready.

**Comment by RamonUnch** [comment]
Try with this one.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5919464/AltDrag.zip) (replace altdrag.exe and hooks.dll in your AltDrag directorry)
The full screen windows should be resized to monior size if AutoRemaximize=1 in the [Advanced] section of AltDrag.ini (middle click on tray icon).
Also by default no full screen windows are disabled, it will be an option in the future.

**Comment by bigcrush** [comment]
I see the same behavior. Go to fullscreen in Firefox with F11. Indeed mouse cursor changes when AltDrag activated but unfortunately no move, no resize of the window. Microsoft Edge(Win10 20H2) in fullscreen mode(F11) acts the same way.

**Comment by RamonUnch** [comment]
Yes this is too bad, unfortunately, unlike a typical Linux desktop which has a lot of abstraction (X server and Window managers) microsoft decided on differnt compromises for Windows.
I will check however if by using the DWM api under windows 10/8 and 7/vista when enabled they can be resized. this is not excluded yet.
Other fullscreen window should work, though, did you try the file explorer with F11?
Also MPV *should* be resized to fullscreen when moving it to another monitor

**Comment by bigcrush** [comment]
It's cool. With 1.37, the fullscreen Firefox window does not move like any other one but jumps between monitor while stays fullscreen. It is strange a bit but more then nothing. Thank you very much.

**Comment by RamonUnch** [comment]
Cool, I was not 100% sure what would happen because I do not actually use a dual monitor setup. But I did try my best for 1.37 to fix the fullscreen problems.

**Comment by RamonUnch** [comment]
Do not forget that to force AltDrag to "try" to move all fullscreen windows you want to set ResizeAll=3 in the [Advanced] section of AltDrag.ini

```
ResizeAll=1
; Set to 1 to be able to resize all windows even those without borders.
; Set to 2 to be able to move/resize all fullscreen windows.
; Set to 3 for both of the above.
```

**Comment by RamonUnch** [comment]
I think I am done with this issue from now.
I may implement a Send F11 option so that a specific list of Windows could receave F11 automatically when moving releasing them.
