### ISSUE TITLE
[Bug] Multiple action menus on multiple clicks

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#213]
A new menu is spawned every time the action menu is invoked without closing the old one.

https://user-images.githubusercontent.com/47380919/178984799-0a48ad19-6b4d-498f-86b7-b7fe154dce28.mp4

Ideally the old instance of the action menu should disappear when a new instance is spawned.

Low priority, but reporting just in case as it's not normal behavior.

**Comment by RamonUnch** [comment]
Could you give me your .ini file? you can zip it then attach it to a post.

**Comment by Ichisich** [comment]
I could replicate the bug.
The culprit is `Move windows with a Long left-click`.

**Comment by RamonUnch** [comment]
This hooks.dll should fix it then.

[hooks1.54test5_x64.zip](https://github.com/RamonUnch/AltSnap/files/9124005/hooks1.54test5_x64.zip)
[hooks1.54test5_i386.zip](https://github.com/RamonUnch/AltSnap/files/9124006/hooks1.54test5_i386.zip)
