### ISSUE TITLE
Feature Request: Setting to define transparency stepping

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#23]
I'd like a way to define how many steps of transparency is changed on Alt + Scroll. And also for Alt + Shift + Scroll. I'm specifically interested in customizing how many steps the Shift scrolling takes as the default step is still too large.

I don't think there is a way to do this currently.

v1.35

**Comment by RamonUnch** [comment]
There is no way for the moment indeed for the moment but it should not be hard.

**Comment by RamonUnch** [comment]
Ok actually this was so trivial that it is already there. 
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5898532/hooks.zip)

Just add AlphaDelta=value between 1-255 (default 8) in the [Advanced] section of ini file
This is the step with shift. Without shift the steps are 8 time marger hence 64 by default.
In your case try 4 and maybe even lower?

**Comment by redactedscribe** [comment]
I was hoping for control over both values. Why? When the stepping is too small, the non-Shift stepping becomes tiresome to scroll up and down. But a small stepping for Shift is convenient for making windows only slightly transparent so the window behind isn't as distracting (this is what I meant when I said default stepping: I cannot make a small enough step, but I personally was fine with the large stepping value). Of course, this may be asking for too much.

In the approach you've already taken, I guess the solution to what I'm asking for is also control over the multiplier value 8x. I could set this then to `16`x when using `4` for `AlphaDelta`.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5898615/hooks.zip)
Simpler to have both values as you say, so if someone wants to invert shift behaviour or something.
now use in [Advanced]
AlphaDelta=64
AlphaDeltaShift=8
You want to modify the AlphaDeltaShift in your case.

**Comment by redactedscribe** [comment]
Something seems wrong. I'm not sure it works as intended.

**Comment by redactedscribe** [comment]
`AlphaDeltaShift=0` still de-/increases, when it should likely do nothing I guess?

**Comment by RamonUnch** [comment]
Yes the value is clamped in the 1-255 range.
I do not know, why you would put 0 maybe to allow only the case where Shift is pressed?
Given that there is no harm to put 0 I will let the user do it.

**Comment by redactedscribe** [comment]
It works as expect as far as I can tell.

Thank you 🙂
