### ISSUE TITLE
Bug with the action menu not disappearing on defocus after second click

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#233]
With the following setting:
![wlCHt1SKdi](https://user-images.githubusercontent.com/47380919/180818508-522ad66e-6515-4e2d-9f83-f1a4fff1e29b.png)
If I invoke the action menu by right clicking on the titlebar,
And then click somewhere else.
The action menu disappears on defocus.

But The second time I invoke the action menu by right clicking on the titlebar
(and subsequent invocations after this),
The action menu does not disappear on defocus and I have to dismiss it with the nothing option on the action menu.

**Comment by RamonUnch** [comment]
If you want extended system menu, I suggest you take a look at https://github.com/AlexanderPro/SmartSystemMenu
I will not extend system menu myself, this was already done a billion times by other software and this would require ugly dll injection in every application, so it is a no-no for me.

**Comment by Ichisich** [comment]
That is a general phenomenon, which varies per application.
Firefox download panel for example also keeps open but updates sporadically.
System menus just don't refresh.

My guess is, it's related to this:
https://user-images.githubusercontent.com/31080003/152984099-34dd0cae-0565-48da-b19b-3e3c82ea13d1.mp4

Windows native resizing and dragging seems to send a stop or nodraw call, which probably is also responsible for terminating some menus and panels. 
Trying to replicate that seems to be very convoluted:
https://github.com/RamonUnch/AltSnap/issues/160#issuecomment-1033645214

Mpv is also a good example. 
Every desktop environment handles it different, Windows and KDE keep the aspect ratio stable, Ubuntu(Unitiy) and AltSnap not.
In most cases, I prefer AltSnap's resizing and dragging over native Windows, as the former is more honest and keeps the content/Information intact.

**Comment by RamonUnch** [comment]
I think a menu closes when it looses focus or if you click outside it. AltSnap dragging does not send a click. Also the Alt key cancel the menu.

**Comment by RamonUnch** [comment]
> @RamonUnch I finally understood what you meant by ugly dll injection when I tried to delete the folder of the SmartSystemMenu after exiting it. I was unable to delete the folder as the dll was locked in by many of the running processes on my pc. I had to use lockhunter to unlock the file to delete it.

Well sorry sometime I talk alone...
The case where you need dll injection is when you need your code to be executed in the context of another process. so for example if you want to modify the system menu (which is filled by th program itself), then you need to inject your code inside the program to modify it. Of course this has the big disadventage that if there is a bug in the injected code, then the program that got the injection may crash.
And in some cases even a perfectly written program could crash because of a bad injected code.
This is the reason I do not want to do this in AltSnap. For now the biggest problem AltSnap can create is to send inconsistent keyboard/mouse data to the program which should not induce big problems.

**Comment by RamonUnch** [comment]
> Yes, clicking outside does close the menu.
But maybe it should send a click first?
That would lead to the natural behavior of the menu disappearing?

I agree sending a click would solve the problem, however it would click and when you drag with AltSnap you do not want to click. It could make you click a button, close the program etc.
So I have no perfect solution.

**Comment by RamonUnch** [comment]
> I mean the click should only be sent in the titlebar drag action. Since the titlebar drag action is smart enough to exclude where the caption buttons are. It shouldn't be a problem.(As the rest of the area excluding the caption buttons is only the titlebar)

This would mostly not be a problem, however some custom titlebars still might have problems.
I will give it a try and maybe add an advanced option.
