### ISSUE TITLE
[Feature request] Option to customize action menu items

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#240]
It would be nice to be able to customize the action menu options.
Right now the list is very long and I just use a couple of options.
It would be better from a user point of view to access the most used options.
Instead of searching for the option you want(especially if it's lower on the list)

Maybe this can be in the advanced options through the .ini file for power users.
So you can rearrange and keep only the options you need.

**Comment by RamonUnch** [comment]
Makes sense indeed.
Keep in mind however that you can use the accelerators key in the menu (t, for topmost, b for borderless etc...

**Comment by RamonUnch** [comment]
Here is a build that allows custom Action menu with the `ACMenuItems` value in the `[Advanced]` section of the .ini file.

```
In the [Advanced] section of the .ini file.

ACMenuItems=-1
; Menu items that will be displayed in the action menu (bit-mask).
; Default is -1 for all menu items.
; If you want only a selection of the menu items, pick them up in the list
; below, sum up the associated numbers and assign the value to `ACMenuItems`
; 1     Toggle Always on top
; 2     Toggle Borderless
; 4     Center window on screen
; 8     Roll/Unroll window
; 16    Lower Window
; 32    Maximize vertically
; 64    Minimize other windows
; 128   Snap To side/corner
; 256   ------------------
; 512   Maximize window
; 1024  Minimize window
; 2048  Close window
; 4096  ----------------
; 8192  Kill program
; 16384 -----------------
; 32768 Nothing
; Example: 32768+1+2+8=32779 Nothing+Topmost+Borderless+Roll
```

Even separators can be configured like this, Of course if you set `ACMenuItems=0` then no menu will be displayed.
[AltSnap1.55test1_i386.zip](https://github.com/RamonUnch/AltSnap/files/9243048/AltSnap1.55test1_i386.zip)
[AltSnap1.55test1_x64.zip](https://github.com/RamonUnch/AltSnap/files/9243049/AltSnap1.55test1_x64.zip)

**Comment by RamonUnch** [comment]
To see the kill option in the action menu you need to booth check this and add 8192 to the value if not already done.

**Comment by RamonUnch** [comment]
> I'm not sure how this option is supposed to work.....
Is it supposed to kill the altsnap process or the process of the active window?

It will kill the process of the pointed window without further ceremony. It is quite aggressive but can be useful sometime.
It will never kill processes that are in the **Processes not to be paused or killed:** blacklist
