### ISSUE TITLE
ini comments confusing for `AeroMaxSpeed` and related settings

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#26]
```ini
AeroMaxSpeed=20
AeroMaxSpeedInt=1
; Speed beyond which AeroSnaps will not occure while Moving.
; AeroMaxSpeed is in pixels/X frames (from 1-65535)
; AeroSpeedInt to specifies the number of frames (default 1) from 1-255.
; To set this value: (i) See the frequency of your mouse and set an
; AeroSpeedInt to average over 10ms or so, so if you have a 1kHz mouse,
; set it to 8-10, if you have a ~100Hz mouse (typical) keep it to 1 or 2.
; (ii) Set AeroMaxSpeed to a "high" value (like 50) and try to move fast
; a window between two monitors, if it get aero-snapped, decrease the value
; until it "just" no longers snaps. (iii) check that the window does snap
; when you want it to sap, if the window tends to restore when you do not
; want increase the AeroMaxSpeed value.
```

It mentions `AeroMaxSpeed` and `AeroSpeedInt`, but not `AeroMaxSpeedInt`.

Perhaps this is outdated? I'm not sure which to use.

Thanks.

**Comment by RamonUnch** [comment]
Actually the comment is right and the two lines should be

AeroMaxSpeed=20
AeroSpeedInt=1

I was not careful when I chose the name...
Will be fixed for sure.

**Comment by redactedscribe** [comment]
No problem.

There is also another small issue: Line 70 begins with a colon: `: Borderless, Roll, Nothing.`, not a semicolon.

Also, the new `MMMaximize=1` option says its works with `left+right`, but in fact it's specifically `left and then right`. Perhaps you can make it so that the window maximizes no matter which order the two mouse buttons are pressed? Hopefully there are no side-effects for allowing `right and then left` click.

**Comment by RamonUnch** [comment]
Thanks for the typo.

It is actually not really left and right but move and resize action (default maps).
In the long term I would like to improve on the mouse button combo so I prefer not to do only one action for any combo in the first place.

For example I could add that when holding the resize button, the wheel can resize the window depending on where it is pointed.

I also plan to add keyboard combo in the future: for example only enable AltDrag when ALT+WIN is pressed this would solve 99% of the interactions with advanced IDEs and could still be pressed with the thumb

For now you can already use several instances of AltDrag to use different hotkeys for different actions, but that's it.

I think the next step will be to add the ability to assign any action to mouse combo.

**Comment by RamonUnch** [comment]
1.37 should have fixed that...
