### ISSUE TITLE
Titlebar Action menu doesn't get dismissed on defocus when left click is set to nothing

### ISSUE THREAD

**Issue by rp1231** [RamonUnch/AltDrag#263]
Titlebar Action menu doesn't get dismissed on defocus when left click is set to nothing

https://user-images.githubusercontent.com/47380919/183671935-0c5996a7-7580-47ee-8185-b4bf684c2041.mp4

The behavior is very inconsistent.

**Comment by RamonUnch** [comment]
Maybe this one will fix it?

[AltSnap1.55test23_i386.zip](https://github.com/RamonUnch/AltSnap/files/9307709/AltSnap1.55test23_i386.zip)
[AltSnap1.55test23_x64.zip](https://github.com/RamonUnch/AltSnap/files/9307710/AltSnap1.55test23_x64.zip)
