### ISSUE TITLE
Disable for fullscreen apps

### ISSUE THREAD

**Issue by loligans** [RamonUnch/AltDrag#32]
When an application is running in fullscreen AltDrag should not be enabled. This is useful for games which might utilize the activation hotkey.

**Comment by RamonUnch** [comment]
I will add an option to have to blacklist all fullscreen windows. However for other fullscreen windows it is desirable that AltDrag remains enabled. It is impossible to detect if it is a game or a fullscreen mediaplayer for exemple.
In the meantime add the program name to your process blacklist. or disablle AltDrag before lunching the game (simple clic on the tray icon).

**Comment by RamonUnch** [comment]
Try this one.
Go in advanced tab and disable the 'Move full screen windows' option.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6091099/AltDrag.zip)

**Comment by RamonUnch** [comment]
Next release will contain this and will apply also to the scroll action.
