### ISSUE TITLE
No longer able to change the transparency of VS Code or Discord

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#43]
In previous versions, Alt Drag was able to affect the transparency of VS Code and Discord.

Firefox can still be affected, so something else is wrong. I tested removing all the blacklist settings, and the programs still do not respond to Alt+Scroll on the window to change transparency. Both problematic applications do respond to Alt+Scroll on the title bar to roll/unroll. Elevating AltDrag does not help. 

`AltDrag v1.40`

**Comment by RamonUnch** [comment]
Strange, I have not changed the transparency code in a while. Did you try to downgrade to v1.39 and verify that it works again?
Also try with 1.41 (that have very small bugfixes but same transparency code).
I will try to figure this out for 1.42...

**Comment by redactedscribe** [comment]
You're right! That makes it work.

The problem is, VS Code or Discord aren't "fullscreen". Both windows aren't touching the screen's edges.

It should be possible to change their transparency when "Enabled on fullscreen windows" is _disabled_. Only when I enable this setting can I change their transparency.

I will try 1.41 now...

**Comment by RamonUnch** [comment]
Older versions were always enabled on FullScreen windows, so when you enable this option you restore the pre 1.39 behaviour.
You mean that you have the problem even when the window is in windowed mode?

Normally for a window to be considered fullscreen it must have no titlebar (but those spetial window may have fake titlebars) and have the full monitor size (be in front of the taskbar).

Maybe the program does not let me obtain the windows rect and I can not detect properly, I will have a deeper look.

**Comment by redactedscribe** [comment]
> You mean that you have the problem even when the window is in windowed mode?

Yes, with "Enabled on fullscreen windows" disabled, I cannot change the transparency. If enabled, I can.

**Comment by RamonUnch** [comment]
So the problem is that I donot detect properly wether or not those windows are actually fullscreen.
I made a small change to the fullscreen detection code, try this one...
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/6177531/hooks.zip)

**Comment by redactedscribe** [comment]
> I made a small change to the fullscreen detection code

It works as expected now, thanks!
