### ISSUE TITLE
Bug: FoxitReader problem when moving/resizing

### ISSUE THREAD

**Issue by SonGokussj4** [RamonUnch/AltDrag#47]
Hi, found a bug with FoxitReader.

When trying to move it with `[LWIN]` and `LMB` by the document content (red example field), it's making the "solitaire" effect. 

When trying to move it outside (green example field), everything works without a problem.

The same problem when trying to resize the window and I grab it by the content.

First App where I noticed a problem with the new AltDrag.

![ALtDragBug](https://user-images.githubusercontent.com/13331858/113192723-6a6cdd80-925f-11eb-8556-6defa230fd91.png)

**Comment by SonGokussj4** [comment]
a) Disabling **MDI support** in AltDrag/Configure resolves this issue.

b) modifying `MDIs=*|PPTFrameClass,*|MMCMainFrame` to `MDIs=*|PPTFrameClass,*|MMCMainFrame,*|classFoxitReader` resolves this issue

If you don't mind me asking, what is the MDIs? Why did it help?

**Comment by RamonUnch** [comment]
MDI means 'multiple document interface'. Moderns software mostly stopped using it.
Those programs have windows within a window: exemple Paint Shop Pro:
![image](https://user-images.githubusercontent.com/74856804/113254255-9d968780-92c6-11eb-9edc-b938ad02bad3.png)

If you enable the MDI option on AltDrag, then you will be able to move windows that are inside the main window of a MDI program. If you do not use any of those programs then you can disable the MDI option and only the main window will be moved.

In some cases programs use the MDI control but are actually not designed as real MDI, this is the case of recent foxit versions, Powerpoint and a few others, those can be added to the MDI.

**Comment by SonGokussj4** [comment]
Thanks for the explanation. That gave me the idea to try it with VBA Editor (VBA programming still lives :-D) and I can finally move and resize the inner windows! Wow! That's awesome.
