### ISSUE TITLE
I can't get the scroll blocklist to work

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltDrag#48]
Doesn't work under process blocklist either for whatever reason

![doesn't work](https://user-images.githubusercontent.com/18603393/113789095-81eb1100-970c-11eb-8f7b-f89d4eaa4867.gif)

ini if you need it:
[AltDrag ini.zip](https://github.com/RamonUnch/AltDrag/files/6267991/AltDrag.ini.zip)

**Comment by RamonUnch** [comment]
`Processes=Virtual PC.exe, photoshop.exe` is a mistake, you need to put `Processes=Virtual PC.exe,photoshop.exe` you Need no spaces after the coma.
`Scroll=|Photoshop` is valid but implies that the window has no title, in your case you would use `Scroll=*|Photoshop` to include all the possible titles.

**Comment by brian6932** [comment]
Ah, thank you so much, I was trying to figure this out for a while now lol
