### ISSUE TITLE
AltDrag stops working when the scaling settings is changed

### ISSUE THREAD

**Issue by zmezei-dpc** [RamonUnch/AltDrag#5]
Steps to reproduce:

- have AltDrag running
- navigate to Display Settings/Scale and layout
- change the  scaling settings to a different value
- AltDrag stops working, the icon is still in the notification area + the process is still running, but the software does nothing (exiting requires killing the process from task manager)

OS is Windows 10 version 20H2 (OB Build 19042.685)

This is an annoying issue, as when Windows turns the screen off and then on (e.g. because of the power settings), it seems that turning on always starts with the 100% scaling setting, and only after that is it changed to the set value. It means that leaving the computer for prolonged times always causes AltDrag to stop working.

I'm not a developer - anything I can help with to eliminate this issue?

**Comment by RamonUnch** [comment]
I thought I had fixed this bug but apparently not.
I really have no Idea of why AltDrag freezes when DPI changes.
It should automatically restart when it receives the WM_DPICHANGED message but sometime windows does not send this message before changing DPI.

I really hope I can fix this issue but in the meantime you can modify your power settings to pprevent display from turning off.

**Comment by RamonUnch** [comment]
It seems related to the tray icon. If you hide the tray icon, it should fix the problem.
I will see what i can do for next release.

**Comment by zmezei-dpc** [comment]
I can confirm, after hiding the tray icon AltDrag survives the DPI change. Thanks for the workaround, much appreciated!

**Comment by RamonUnch** [comment]
I found the bug, keep an eye for next release, it will be fixed for this week-end.

**Comment by zmezei-dpc** [comment]
Confirmed, 1.33 fixes this issue. Thank you very much!
