### ISSUE TITLE
Snap Threshold has no effect

### ISSUE THREAD

**Issue by Turbine1991** [RamonUnch/AltDrag#50]
I believe this setting is to allow you to specify the distance a window will begin snapping.

Unfortunately setting this to even 100 will not affect the distance for tiling. This setting is most useful for those of us with multi-screen setups.

**Comment by RamonUnch** [comment]
Which AltDrag version are you using? be sure to use the latest version.
Be sure that the hooks.dll is properly updated as well (version should match AltDrag.exe's one)
There are two thresholds:

*Snap Threshold (default 20 pixels) is the distance in pixels at which the windows borders will snap to each other (magnetic). You need to press shift or to enable it in the options ([General]->Snap windows edges:...).
*Aero snap (default 5) is the distance in pixels between the cursor and the monitor sides at which the window will aero-snap to fill a fraction of the monitor. Maybe this is what you wanted to change.

**Comment by RamonUnch** [comment]
Note that to aero-snap a windows between two monitors, you can press Ctrl or Shift and it will restrict the cursor to the current monitor.

**Comment by Turbine1991** [comment]
> *Aero snap (default 5) is the distance in pixels between the cursor and the monitor sides at which the window will aero-snap to fill a fraction of the monitor. Maybe this is what you wanted to change.

This is exactly what I was looking for. The naming is a little ambiguous, I suppose Tiling Threshold would be the term in Linux.

> Note that to aero-snap a windows between two monitors, you can press Ctrl or Shift and it will restrict the cursor to the current monitor.

That's neat!
