### ISSUE TITLE
Is zones layout configuration bugged?

### ISSUE THREAD

**Issue by akamienski** [RamonUnch/AltDrag#553]
Hello,

so I've recently discoverd AltSnap and I want to replace FancyZones with it. I want to configure very simple layout - screen seperated into two even pieces on the sides, and maybe have additional layout with 3 vertical zones (which is a default layout). I've tried to configure it using snap layout configuration by creating two test windows on the sides and saving this as a layout 1, I've also tried to configure it directly in ini file, run AltSnap as elevated and non-elevated, toggle many different configuration options and nothing works! Snap layouts remains exactly the same, seperating screen into three vertical windows or 2 horizontal windows. Holding alt+win key or holding alt and swiping touchpad gives the exact same result I mentioned above. I even removed certain parts of properties under [Zones] in ini file to see how snapping will behave then - literally nothing changes. I use verison 1.63.

Is it actually bugged or I just don't get it how it works and how should it be configured? What I would like to achieve is how Rectangle on macOS works - specific key combination snaps window to specific position, like ctrl+alt+left arrow key snaps to the left side, ctrl+alt+right to the right side, ctrl+alt+up maximizes window and etc.

**Comment by RamonUnch** [comment]
To snap a window to a zone, you need to use press shift+Alt+Click and drag the window over the zone.
