### ISSUE TITLE
Snapping to resized snapped window.

### ISSUE THREAD

**Issue by KoleckOLP** [RamonUnch/AltDrag#58]
Default Windows Aero snapping can snap windows to another snapped windows even if the other window was resized.

Could this be added to this program?

**Comment by RamonUnch** [comment]
Good point.

For now when you resize a window that was snapped by AltDrag, it instantly clears the **snapped flag**.
Also the `AeroMoveSnap()` function snaps windows to a fixed fraction of the monitor.

I will see if I can improve upon that.

**Comment by RamonUnch** [comment]
I had some time tonight to make quick modifications.

Have a try with this version of [hooks.zip](https://github.com/RamonUnch/AltDrag/files/6518046/hooks.zip)

Quit AltDrag, replace the hooks.dll then re-lunch AltDrag.

With this version a snapped then resized window will still be restored to its pre-snapped dimentions when restored by move.

When you snap a window to the right or left and resize it, the next window snapped to the other side thould fill up the remaining space.

For now if you have several snapped windows that you resize in all directions, the sizes will not always be smart. but for most cases it should work.

**Comment by KoleckOLP** [comment]
It works, I have found one issue tho,

If I snap a window using AltDrag, resize it and snap another one to it it work exactly like I wanted it to.

But if I AeroSnap a window, resize it and that want to AltDrag snap another window to it it snap to the defaul size.

xD if I get used to AltDragging everything the current implementation is great. But I am still learning, and adapting my workflow to AltDrag.

I also want to thank you for the really fast responce time!

**Comment by RamonUnch** [comment]
> But if I AeroSnap a window, resize it and that want to AltDrag snap another window to it it snap to the defaul size.

For now you cannot mix both kind of snapping (aero-snapping and AltDrag-snapping) and have auto-sizing.
It should be a possible to make altdrag aware of aero-snapped window but not the other-way around though.
because it is impossible to use the same snapping functions that window uses.

**Comment by KoleckOLP** [comment]
Could you please make AltDrag be avare of Aero snapped windows?
Seems to be like a good compromise.

**Comment by RamonUnch** [comment]
Well after a bit more work, ,this one *should* work on normally snapped windows.
I could not test on Win 10 yet but just on the good old Win 7...
It will be an optional parameter in the next release.
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/6526398/hooks.zip)
If you can already set `SmartAero=0 `in the `[General]` section of `AltDrag.ini` to disable the new feature.

**Comment by KoleckOLP** [comment]
I've just tried t on my Windows 10 PC, and if I Aero nap a window to the right resize and AltDrag snap a window to the left it works as intended.

But if I Aero snap window to top left 1/4 of the screen as resize it's height and try to AltDrag snap a window to the bottom left it does not match the size of the Areo window and snaps to default size.

**Comment by RamonUnch** [comment]
For now it only considers the horizontal coordinates. It will be improved when I reach my Win 10 computer.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/6530833/hooks.zip)
Here is a fixed version that should consider both horisontal and vertical offsets.

There are small differences with normal snapping but I think it is quite decent now.

**Comment by KoleckOLP** [comment]
Yap looks pretty good to me! Thank you!

**Comment by RamonUnch** [comment]
Present in AltDrag 1.44
