### ISSUE TITLE
Crash when moving or resizing on secondary monitors

### ISSUE THREAD

**Issue by Nordskog** [RamonUnch/AltDrag#6]
### Problem:
When using `alt + left-click` to move a window on my secondary monitors ( Left, right ), AltDrag crashes and then immediately relaunches itself, causing its tray icon to flicker, and the window not to be moved.

`Alt + middle-clicking` to maximize/restore a window works as expected, even on the secondary monitors, while `alt + right-clicking` to resize will crash it just like `alt + left-clicking` to move.

Everything works fine on the man display (center monitor with taskbar, "Make this my main display" checked ), including `alt + left-click` to move and `alt + right-click` to resize 

If I check "Make this my main display" for either of the other monitors, it will work on that monitor, and stop working on the other monitors.

When moving a window from the primary center monitor to the left or right monitors, AltDrag crashes the moment the cursor passes over the border.

### Setup: 
AltDrag version 1.32
Windows 10 2004 ( Updated to 20H2, no change )
AMD Ryzen 3900x
RTX 2070 Super

Monitors:
Left: 1080p HDMI ( Scaling 100% )
Center: 4k DisplayPort ( Scaling 200% )
Right: 1080p HDMI ( Scaling 100% )

I would include a crash log, but have been unable to find any. It does not appear in Window's event manager either.
This is a wonderful tool, and Instructions on how to proceed to acquire useful debug information would appreciated.

**Comment by RamonUnch** [comment]
There is no crash log for now.
Could you try 100% scaling on the center monitor? there are some crash/freezing associated with dpi changing that I really cannot figure out at this point.

I do not have multiple monitors, so I can only do very few tests from time to time, using my laptop with an extra screen.

**Comment by RamonUnch** [comment]
Try with this one
[AltDrag1.322.zip](https://github.com/RamonUnch/AltDrag/files/5781027/AltDrag1.322.zip)
Replace AltDrag.exe and hooks.dll (quit AltDrag first).

**Comment by Nordskog** [comment]
> 
> 
> Try with this one
> [AltDrag1.322.zip](https://github.com/RamonUnch/AltDrag/files/5781027/AltDrag1.322.zip)
> Replace AltDrag.exe and hooks.dll (quit AltDrag first).

That did the trick! 
Everything appears to be working fine now; both moving/resizing on secondaries and moving between monitors.

Thank you!
