### ISSUE TITLE
Blacklist: Partial Name Match

### ISSUE THREAD

**Issue by mdroidian** [RamonUnch/AltDrag#64]
Is it possible to do partial name match?

I have the Todoist chrome app which, similar to notepad.exe, includes the name of project you are in with it's title.

`MyProject: Todoist|Chrome_WidgetWin_1`

Therefore I can't seem to blacklist it without blacklisting chrome as well.  I tried:

`*Todoist|Chrome_WidgetWin_1` but that didn't work.

Ps. Awesome app! ♥

**Comment by RamonUnch** [comment]
For now the `*` character is only used to globally include all titles or all classes, so only `*|class`  and `title|*` formats are supported.
This will be improved. in the future.
Why do you need to blacklist just this window?

**Comment by RamonUnch** [comment]
The WIP issue is here https://github.com/RamonUnch/AltDrag/issues/61
For now what you want to do is not supported yest as the `*` has to be at the end of the title or class.

**Comment by RamonUnch** [comment]
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6611117/AltDrag.zip)
Quick improvement because I have a free evening, here is a version of AltDrag that supports the format:
`*end of title|begining of class*` in the blacklist

**Comment by mdroidian** [comment]
Wow!  Thank you.  I can go back to `Alt` now and blacklist Todoist. 😁

**Comment by RamonUnch** [comment]
Present in AltDrag 1.44
