### ISSUE TITLE
Wiki, tiny spelling mistake 😉

### ISSUE THREAD

**Issue by mdroidian** [RamonUnch/AltDrag#66]
The blacklist link in the TOC links to

https://github.com/RamonUnch/AltDrag/wiki#blacklist

But the anchor has an 's', so it doesn't work.  Just FYI 😊

https://github.com/RamonUnch/AltDrag/wiki#blacklists

**Comment by RamonUnch** [comment]
Thanks, fixed, do not hesitate if you find more errors.
