### ISSUE TITLE
Separate both scroll wheel action

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltDrag#69]
[AltDrag-1.44-test11.zip](https://github.com/RamonUnch/AltDrag/files/6643708/AltDrag-1.44-test11.zip)

![image](https://user-images.githubusercontent.com/74856804/121803193-a5689580-cc40-11eb-8196-a12ff3ac8a15.png)
As you can see the action for the horizontal scroll wheel (for those that have one) can be selected independently.
@Nostaljaded, You could give it a try because it seems you do have a Hardware Horizontal scroll wheel.
I could not test it with real hardware yet.

**Comment by Nostaljaded** [comment]
`Horizontal scroll` mouse actions doesn't work with test11 build; it just reversed the horizontal scroll direction in Chromium even though it's set to `Volume`.

Adjusting volume by `Scroll wheel` mouse actions worked, as expected.

**Comment by RamonUnch** [comment]
[AltDrag-1.44-test12.zip](https://github.com/RamonUnch/AltDrag/files/6653320/AltDrag-1.44-test12.zip)
I guess I found the bug,
Have a try with the above build...

**Comment by Nostaljaded** [comment]
As of test12, `Horizontal scroll` direction is correct. In other words, as expected.

**Comment by RamonUnch** [comment]
Present in AltDrag 1.44
