### ISSUE TITLE
Aero Snap: Dragging via title bar after snapping does not restore original window dimensions

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#7]
If I recall correctly, after snapping a window to a corner for example, Windows' Aero Snap would restore the window's original dimension when dragging it back to the center of the screen. This does work if you hold your defined hotkey and drag the window (dimensions restored), but sometimes one reaches for the title bar. The way to "get back" your window dimension is:

1. Drag window to the screen's edge and snap it to the corner.
2. Drag it back away to the center of the screen via its title bar (window shape is now that of the corner snap).
3. Perform a Move via your set hotkey and AltDrag restores the window's original dimensions (if performing a Resize however, the dimensions are overwritten / i.e. lost).

If AltDrag could somehow handle this scenario, I'd be grateful.

Also, it may be worth considering clarifying the two features with "snap" in the name. i.e. renaming "Automatically snap to:" => "Snap window edges to:".

Finally, despite this having removed some features compared to the original, it still may be worth linking the [original documentation](https://stefansundin.github.io/altdrag/doc/) somewhere.

Thanks for forking this by the way 🙂

```
AltDrag v1.32
Windows 10 20H2
```

**Comment by RamonUnch** [comment]
Unfortunately Microsoft provides no interface to acess any of the native snapping state.
This means that AltDrag re-implements ALL the snapping by himself and it is impossible (as far as I know) to properly mix both kind of aero snapping.

I will see for the funny behavior you describe and for the snapping terms.

**Comment by redactedscribe** [comment]
There is a commercial software named [AquaSnap](https://www.nurgo-software.com/products/aquasnap#t3-mainbody) which can do this if I understand correctly. The function is available in the [free version](https://www.nurgo-software.com/pricing/aquasnap) too should you want test it, so it is possible, but how, I do not know. I could instead rely on AquaSnap for this feature alone, and disable it in AltDrag. Other than this inconvenience, AltDrag and AquaSnap are fairly equal at aero-snapping I believe.

**Comment by RamonUnch** [comment]
Acqua Snap goes beyond in term of snapping with the tiling mode and groupped windows.
I will take a deeper look into this, but i guess it uses injected dll to overtake normal windows moving/snapping, like altdrag did with the hookswindows option that I removed.

**Comment by redactedscribe** [comment]
That may be the case. Thank you for having a look at least 🙂

**Comment by icyhoty2k** [comment]
Yes I agree that auqasnap is worth taking a look at , there are many ideas that can be implemented in altDrag i give a thumbs up if you have time(nerves) to  investigating AquaSnap and try to implement some thins into altDrag.

**Comment by RamonUnch** [comment]
Actually I found a solution to this problem. it seems that if a window was snapped, even though it is in a "restored" state, the WM_RESTORE command can be sent to it and it will, restore the previous position.
Try with this hooks.dll
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5807635/hooks.zip)
Tell me if it works for you.

For Acqua Snap, I will see more in details what can be implemented without too much work.

**Comment by redactedscribe** [comment]
I closed AltDrag (and AquaSnap), replaced Hooks.dll, and re-ran the program. The behavior is still the same as far as I can tell. No improvement unfortunately.

I don't think there is much more that I'd like from Aqua Snap myself. Maybe the AquaGlue tab's features (resize aero-snapped windows together if they are touching). And/or perhaps the easier to implement, AquaStretch (double-clicking window borders to extend a window in the given direction until the screen border - currently, doing this sends the Maximize/Restore (which can also be done by just double-clicking within the window)).

Also, AquaSnap handles aero-snapping windows a little nicer: Given a dual monitor setup, with a window on the left monitor, dragging it to the left requires it to be ~5px close to the edge before the aero-snapping is effective, but then dragging the window to the right edge (middle of both monitors) the threshold is much bigger (~32px) making it easier to snap (as opposed to having to use AltDrag's Ctrl to lock the cursor to the current monitor (there is also a bug with this it seems)). Perhaps AltDrag could do something similar, making holding Ctrl less necessary.

**Comment by RamonUnch** [comment]
Strange, probably due to the fact I have a single monitor,
Try again with this one...
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5808927/hooks.zip)

**Comment by redactedscribe** [comment]
Still the same. Just to be clear, I'm dragging a window and aero-snapping it to the left side of my left screen, then dragging it back to the center via the title bar. The window shape/dimensions stay the same. They are not restored (unless performing the additional step I mentioned in the first post).

**Comment by RamonUnch** [comment]
I fixed the inverse problem.

**Comment by redactedscribe** [comment]
Maybe I'm missing something, but I cannot find a functional difference regarding this issue between 1.32's `hooks.dll` and the one you just provided. Thank you though.

**Comment by RamonUnch** [comment]
When snapping with the titlebar (normal windows snapping) and then moving with Alt, it should restore the window size.
I will see how I can do the same in the other way you described: snap with Alt then try to restore with normal movement.

**Comment by redactedscribe** [comment]
Ah yes, you are correct. It works as you describe.

There is a glaring issue with this though: after normal windows snapping a window, a list of windows on the opposite side is shown: suggested windows which can be snapped next to the window you just snapped. If you do not close this before Alt-dragging your window back to the center, half of the screen will still be a list of thumbnail previews of other windows. An easy fix is to just turn that Windows feature off (which I have): 
![disable](https://user-images.githubusercontent.com/25013746/104465174-6e705400-55bc-11eb-8426-c078dbc34cf5.jpg)

**Comment by RamonUnch** [comment]
Probably I should prevent any Alt-dragging if this window is present or maybe even close it.
I do not use this option myself, I will re-enable it to see.

**Comment by redactedscribe** [comment]
I think it's best to just prevent dragging until that window is no longer present. That would let users use this Windows feature if they want to.

**Comment by RamonUnch** [comment]
It seems to be a very special window, I do not know how to detect it.
However it does not seem a big issue to me, you just have to click if you want it to go and it can still be used to handle other windows...
It is in my todo list though.

**Comment by RamonUnch** [comment]
Try This hooks.dll
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5873469/hooks.zip)

And use the Later AltDrag 1.35 (to be sure)
For the moment you NEED the "Lower windows by middle clicking on title bars" option ENABLED if you want to be able to restore from the title bar a windows that was AltDrag snapped.
It will be a separated option in the future.

There is also a remaining issue: when you click on minimize button, the window is restored.
This is because Windows 10 is buggy and gives the same signal than when clicking on the rest of the title bar when it should not according to the DOC.
I will see what I can do with this...

This fix should be in the next release, tell me if it fixes it for you.

**Comment by redactedscribe** [comment]
> Try This hooks.dll

It works great!

> There is also a remaining issue: when you click on minimize button, the window is restored.

I'm not sure when clicking minimize causes this problem, but every scenario that I quickly tried, minimize did not restore, but minimized the window as expected.

**Comment by RamonUnch** [comment]
Good that you do not have this issue, however fort the release, you will have a separated option and you will also need to drag the window in order to restore it (like with normal snapping) instead of just a simple click which is undesirable.

**Comment by redactedscribe** [comment]
Perhaps this is expected, but when dragging the title bar for Windows Terminal, it is not restored to its normal window size. This only happens with `MMBLower=*|CASCADIA_HOSTING_WINDOW_CLASS` key value in the `AltDrag.ini`. When the line is commented, the newly fixed behavior is working again.

**Comment by RamonUnch** [comment]
[hooks.zip](https://github.com/RamonUnch/AltDrag/files/5882139/hooks.zip)

Ok, this one should Fix MinAppha as well as the fact MMBLower blacklist was applying to the restore option.
This restore option is not enabled by default because it requires a constant mouse hook.
In the [General] section of your AltDrag.ini set:

NormRestore=1
; Allow restoration of AltDrag-aerosnapped windows 
; with a simple click on the title bar (default 0: Off).

For me it does defocus lowered windows for for some of them but less than before, I will invistiigate...

**Comment by RamonUnch** [comment]
By the way this later version has an additional feature:
Alt+Shift+Double-right-click on a window will extend its side/corner to the monitor borders.
The same without shift behaves as before and aero-snaps in the selected border/corner.

**Comment by redactedscribe** [comment]
`MinAlpha=0` works perfectly now.

I tried `NormRestore=1` but it didn't seem to work in any [section]. No windows restore themselves after aero-snap now.

Is a "constant mouse hook" potentially a bad thing for games and anti-cheat?

An idea for another Alt+_Shift_ resize combination:
It would be cool if Alt+Shift when _right-click_ dragging from the _center_ of the window (`ResizeCenter=1`), only expanded left/right, or up/down, instead always in all directions. Ideally, you would be able to grab anywhere inside this center box, and if you click-and-drag for over maybe 10px(?) left/right, then resize both `+x`/`-x` until releasing the mouse button. If up/down is the first to be clicked-and-dragged over 10px(?), then do the same but for `+y`/`-y`. Maybe there is a way to change your mind after starting left/right, or it could just be locked until your next click.

**Comment by RamonUnch** [comment]
Strange that it does not work for you, can you attach your full ini file?

It seems a good Idea, to resize only the borders towards which you are moving instead of all directions

I advise you to give a try to the 'Bottom right' mode for the 'resize center mode' option (which I personally use). The All direction mode is always a mess but is default for most Linux distro.

An other way if you donot like the center resize mode is to set CenterFraction=0 to have only 4 corners resize mode.

Try in case with this .ini file
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5882848/AltDrag.zip)

Finally the fact that the mouse hook is always on should not be a major concern but outside of LowerWithMMB and Scroll inactive windows (not needed under win 10) and this later option, normally the mouse should be hooked only wen Alt is pressed.

This should not be a problem for you because you already use LowerWithMMB option, so your mouse is always hooked.
As window can destroy the hook without warning, this may lead to a situation where AltDrag stops working for a few seconds. Also if there is a bug in the program it is more likely to lock your mouse (only for a time though).

**Comment by redactedscribe** [comment]
I'm not sure why, but dragging Windows Terminal window away via its title bar (after aero-snapping it to the side), now restores the window to it's previous dimensions. It didn't seem to work at all last night, but now does. Also, it doesn't matter if `NormRestore=1` is present in the file or not, it always restores its dimensions. Maybe because the mouse is already hooked? But you claim the default for `NormRestore` is 0. Anyway, here's my [AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/5885257/AltDrag.zip). Your zip worked fine too.

**Comment by RamonUnch** [comment]
Those are nice feature request
I will see if i can add the 'roll window' action or/and maybe add it on Alt+Shift+DoubeLeftClick.

There is a list of interesting feature requests in this thread, could you copy/paste them in separated issues with the proper names? This would be helpfull.

So your issue was only with Windows Terminal? Other windows behave correctly?
As for a test window the most "normal" one that is always available is notepad's one.
This is a good idea to make a test window that would draw the resizing zone on itself, this is GUI developpement though and is lower on my priority for now.

**Comment by RamonUnch** [comment]
Also when restoring normally there is a small area between the resize border and the caption that is tagged as sizing but does not resize and moves instead. This explain why when clicking on the very top of a title bar sometime it does not restore...
It is just 1 pixel I think...

**Comment by redactedscribe** [comment]
> So your issue was only with Windows Terminal? Other windows behave correctly?

I was testing because with `MMBLower=*|CASCADIA_HOSTING_WINDOW_CLASS` present, it was not restoring. With your latest hook, Windows Terminal and other programs restore correctly when dragging the window back to the center via its title bar.

**Comment by RamonUnch** [comment]
Perfect thanks for your work.
Given that feature requests were ported now, I close this issue

**Comment by redactedscribe** [comment]
@RamonUnch The issue appears to have returned (I don't know when, and was this actually ever resolved?):

- Hold Alt and drag a window to the monitor's edge to snap it.
- Drag the now snapped window by its title bar to the middle of the screen and notice that the window dimensions are the same as when it was snapped (i.e. the original dimensions before snapping were not restored).
- **Optional:** You can also now hold Alt and drag the window again and notice that the original dimensions of the window are instantly restored when they should have already been restored by the dragging of the title bar.

Thanks.

**Comment by RamonUnch** [comment]
Which was the previous version you were using?
Since version 1.50 the Titlebar actions were generalized, so if you want windows to be restored by AltSnap you need to enable the Movement inside the titlebar:

```
== AltSnap 1.50 ==

 * New: Major changes in the title bar handling. A set of specific actions
   can be configured for each mouse button to apply when clicking on the
   title bar. Those actions can be configured to be used without pressing
   the hotkey if you want. This replaces all special title bars options:
   `LowerWithMMB`, `RollWithTBScroll`, `NormRestore`, `TitlebarMove`,
   now removed. **CHECK YOUR CONFIG** when you install this update...
...
```

**Comment by RamonUnch** [comment]
I guess you were using a pre-1.50 version and you were using the `NormRestore` option.
There is no perfect equivalent since 1.50. What you can do is set the Titlebar action for the left click to the Move action, this would be equivalent to the old `TitlebarMove` option.

**Comment by redactedscribe** [comment]
> Which was the previous version you were using?

I'm using 1.56, but I only just noticed this, I upgraded when 1.56 was released and the issue may have been present before then too, so yes, it may be something that was only possible pre-1.50.

I'm not sure if we've understood each other: When I said hold Alt drag and snap a window to the monitor's edge, for example the corner, the window shrinks into 1/4 the size of the screen. After this, dragging this window via its title bar does not restore the window to its previous dimensions which I expect that it should. If you want to restore the windows dimensions, instead of dragging the 1/4-sized window away from the corner via the titlebar, hold Alt and drag the window away (this is the only way that works).

Shouldn't both ways result in the window's original dimensions being restored?

**Comment by RamonUnch** [comment]
> Shouldn't both ways result in the window's original dimensions being restored?

Not since 1.50 because the `NormRestore` option was removed as it was redundant with titlebar action:

![Image1](https://user-images.githubusercontent.com/74856804/188234119-c844af84-c082-4e97-9830-62d58f5c6a61.png)

The `NormRestore` option was removed because it was a lot ad-hock coding and it is almost equivalent to setup Move for the Left click in the Titlebar action

**Comment by redactedscribe** [comment]
I've set Title bar's Left mouse button action to Move window and it works like I was expecting now. Thanks!

However, there is another issue: If I simply drag a window by its title bar to the edge of the screen and aero snap it (the native Windows feature) to take up the left half of the screen for example, dragging the window back by its title bar doesn't return the window to its original dimensions. So a similar issue. If instead of dragging the window back by its title bar you use Alt + drag, the window shape is restored after a Windows aero snap. Can this happen for the title bar also?

**Comment by RamonUnch** [comment]
>However, there is another issue: If I simply drag a window by its title bar to the edge of the screen and aero snap it (the native Windows feature) to take up the left half of the screen for example, dragging the window back by its title bar doesn't return the window to its original dimensions. So a similar issue. If instead of dragging the window back by its title bar you use Alt + drag, the window shape is restored after a Windows aero snap. Can this happen for when dragging back via the title bar also?

1) When you Sap a window with AltSnap, the restore data are only available for AltSnap. By default when you move via the Titelabr AltSnap does not kick in so window cannot guess that the window was snapped with AltSnap.
2) When you snap a window normally, the restore data can be determined by AltSnap (even though i is not documented by Microsoft). So when You drag a window using AltSnap it always should get restored.
3) If you setup Move for the Left click in the Titlebar action then AltSnap will always be used for Snapping, moving and restoring the windows. So you should have a perfectly consistent experience.

**Comment by RamonUnch** [comment]
> Oddly, the above does actually work sometimes, but others times not. Interestingly, the behaviour is different even between two Firefox windows (one launched as a new window from the other). There is a bug here, but I'm not sure what. It seems to work on all other windows, but one Firefox window doesn't restore itself 100% of the time when dragging back via the title bar.

So you mean that even with the above settings some windows are not restored properly? This is a bug, then, I would open new issue.

**Comment by RamonUnch** [comment]
Note that you can visually identify if the window was moved by AltSnap by noting the presence of the Hand cursor. If the Move action kicked in, then the cursor turns into a hand, otherwise true native window movement will show the normal cursor.

**Comment by RamonUnch** [comment]
Also If you resize a snapped window the restore flags gets cleared unless the Smart Aero Snap dimensions option is checked (General tab), should be checked by default.
