### ISSUE TITLE
Enable/Disable AltDrag based on Scroll Lock state

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/AltDrag#71]
Here is a new option for AltDrag, that allows you to have it enabled only when the **Scroll Lock** key is toggled on.
This is a simple and easy way to enable/disable it.

https://github.com/stefansundin/altdrag/issues/10
https://github.com/stefansundin/altdrag/issues/28

test build: [AltDrag-1.44-test13.zip](https://github.com/RamonUnch/AltDrag/files/6662450/AltDrag-1.44-test13.zip)
You have to enable the option in the **Keyboard** tab.

**Comment by RamonUnch** [comment]
Present in AltDrag 1.44

**Comment by Nostaljaded** [comment]
Using `Scroll Lock` to enable/disable AltDrag does not update the AltDrag tray icon status, like enabling/disabling through the tray icon menu.
Currently if AltDrag is disabled by tray icon menu, `Scroll Lock` does not enable AltDrag.

![1](https://user-images.githubusercontent.com/28423237/123193048-10e90900-d472-11eb-8e92-59f6d59efab2.png)

*If the intention for `Scroll Lock` is to work differently from tray icon menu*, wording should be change to `Suspend/Unsuspend AltDrag based on Scroll Lock state` and a new tray suspend icon will be needed.

FYI: My keyboard does not have LED indicator for `Numlock` & `Scroll Lock`.

Tested on AltDrag 1.44 public release.

**Comment by RamonUnch** [comment]
AltDrag is not really disabled, nor suspended, it just ignores all keys unless Scroll lock is activated.

Good point for the tay icon.
I did not add it for simplicity sake. This option only takes 3 lines of code for now.
I figures the LED indicator would be enough but apparently not always.
Thanks for your comment, It will be improved upon in the future.

**Comment by RamonUnch** [comment]
Try with this one; you will have an arrow with a suspension point `...` when AltDrag is suspended.
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6708380/AltDrag.zip)

**Comment by RamonUnch** [comment]
Present in 1.45
