### ISSUE TITLE
Feature Request: Inverted Scroll Lock toggle

### ISSUE THREAD

**Issue by brian6932** [RamonUnch/AltDrag#73]
So with 1.44 there was a Scroll Lock toggle added, however, it only works one way, I think it would be pretty useful to have an inverted function for it, cause personally, I don't have my Scroll Lock on by default, and I know I can toggle this in bios, but I have other programs that are disabled when Scroll Lock is turned on, so it would be nice for software compatibility

**Comment by RamonUnch** [comment]
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6702020/AltDrag.zip)
Set manually  `ScrollLockState=3` in the `[Input]` section of `AltDrag.ini` and you are done.

**Comment by RamonUnch** [comment]
Fixed in 1.45
