### ISSUE TITLE
Wrong state of hotkeys after returning from screen lock

### ISSUE THREAD

**Issue by scx** [RamonUnch/AltDrag#74]
Some actions are performed even when the hotkeys are not pressed.

## Steps to reproduce

1. Install AltDrag _1.0_-_1.44_.

2. Run AltDrag.

3. Setup AltDrag

    3.1. Set scroll whell action to _Transparency_.

    3.2. Set _Left Alt_ and _Right Alt_ as the hotkeys.

    3.3. Make sure that the _Combo Keys_ option is disabled.

4. Open one or more Explorer windows (e.g. Documents, Pictures, etc.).

5. Test changing window transparency by pressing `Alt`-`Scroll Up/Down`.

6. Lock screen by pressing `Alt`-`Ctrl`-`Del`, then _Lock_.

7. Press `Ctrl`-`Alt` when screen is locked. Repeat two times to be sure.

8. Enter your password, then press `Enter` to return to your desktop.

9. Don't press any key. Just hold the mouse cursor over a window, then scroll up/down using scroll wheel.

## Expected results

Nothing special should happen from the AltDrag. You may scroll window content or perform any other default scroll action.

## Current results

Although hotkeys are not pressed, the selected window changes transparency level.

## Notes

You can get similar results with any other scroll wheel actions, e.g. _Alt-Tab_, _Volume_, _Lower Window_, _Maximize Window_, etc.

This bug doesn't appear for middle mouse button actions.

It also doesn't affect left and right mouse button actions.

## Explanation

AltDrag tries to check key state when possible. Unfortunately, it is unable to record release of the mentioned keys when lock screen is enabled.

## Solution

AltDrag should check the state of the keys more carefully.

## Temporary patch

`AltDrag-1.44-AltState.diff` (git diff):
[AltDrag-1.44-AltState.diff.txt](https://github.com/RamonUnch/AltDrag/files/6708481/AltDrag-1.44-AltState.diff.txt)
https://pastebin.com/raw/L1vtAW0K

```
diff --git a/hooks.c b/hooks.c
index 3b73432..221fb0e 100644
--- a/hooks.c
+++ b/hooks.c
@@ -1570,6 +1570,30 @@ static void SetForegroundWindowL(HWND hwnd)
         PostMessage(state.mdiclient, WM_MDIACTIVATE, (WPARAM)hwnd, 0);
     }
 }
+// Return true if required amount of hotkeys are holded.
+// Defaults hotkeys are left and right Alt.
+// If KeyCombo is disabled, user needs to hold only one hotkey.
+// Otherwise, user needs to hold at least two hotkeys.
+static int AltState()
+{
+    // required keys, default 1
+    UCHAR rkeys = 1;
+    // if KeyCombo is enabled, one more key is required to be holded
+    if (conf.KeyCombo) rkeys++;
+    // current keys
+    UCHAR ckeys = 0;
+    // loop over all hotkeys
+    struct hotkeys_s *hk = &conf.Hotkeys;
+    UCHAR *pos=&hk->keys[0];
+    while (*pos && ckeys < rkeys) {
+        // check if key is held down
+        if (GetAsyncKeyState(*pos)&0x8000)
+            ckeys++;
+        pos++;
+    }
+    // return true if required amount of hotkeys are holded 
+    return ckeys >= rkeys;
+}
 // Returns true if AltDrag must be disabled based on scroll lock
 // If conf.ScrollLockState&2 then Altdrag is disabled by Scroll Lock
 // otherwise it is enabled by Scroll lock.
@@ -2698,8 +2722,11 @@ LRESULT CALLBACK LowLevelMouseProc(int nCode, WPARAM wParam, LPARAM lParam)
             return CallNextHookEx(NULL, nCode, wParam, lParam);
         }
     } else if (wParam == WM_MOUSEWHEEL || wParam == WM_MOUSEHWHEEL) {
-        int ret = WheelActions(pt, msg, wParam);
-        if (ret == 1) return 1;
+        // Force check of hotkeys state
+        if (AltState()) {
+            int ret = WheelActions(pt, msg, wParam);
+            if (ret == 1) return 1;
+        }
         return CallNextHookEx(NULL, nCode, wParam, lParam);
     }
 
```

`AltDrag-1.44-AltState.patch` (diffutils patch):
[AltDrag-1.44-AltState.patch.txt](https://github.com/RamonUnch/AltDrag/files/6708482/AltDrag-1.44-AltState.patch.txt)
https://pastebin.com/raw/JL2gw1vT

```
diff -au AltDrag.orig/hooks.c AltDrag/hooks.c
--- AltDrag.orig/hooks.c	2021-06-24 11:44:43.919604500 +0200
+++ AltDrag/hooks.c	2021-06-24 12:29:54.988818800 +0200
@@ -1570,6 +1570,30 @@
         PostMessage(state.mdiclient, WM_MDIACTIVATE, (WPARAM)hwnd, 0);
     }
 }
+// Return true if required amount of hotkeys are holded.
+// Defaults hotkeys are left and right Alt.
+// If KeyCombo is disabled, user needs to hold only one hotkey.
+// Otherwise, user needs to hold at least two hotkeys.
+static int AltState()
+{
+    // required keys, default 1
+    UCHAR rkeys = 1;
+    // if KeyCombo is enabled, one more key is required to be holded
+    if (conf.KeyCombo) rkeys++;
+    // current keys
+    UCHAR ckeys = 0;
+    // loop over all hotkeys
+    struct hotkeys_s *hk = &conf.Hotkeys;
+    UCHAR *pos=&hk->keys[0];
+    while (*pos && ckeys < rkeys) {
+        // check if key is held down
+        if (GetAsyncKeyState(*pos)&0x8000)
+            ckeys++;
+        pos++;
+    }
+    // return true if required amount of hotkeys are holded 
+    return ckeys >= rkeys;
+}
 // Returns true if AltDrag must be disabled based on scroll lock
 // If conf.ScrollLockState&2 then Altdrag is disabled by Scroll Lock
 // otherwise it is enabled by Scroll lock.
@@ -2698,8 +2722,11 @@
             return CallNextHookEx(NULL, nCode, wParam, lParam);
         }
     } else if (wParam == WM_MOUSEWHEEL || wParam == WM_MOUSEHWHEEL) {
-        int ret = WheelActions(pt, msg, wParam);
-        if (ret == 1) return 1;
+        // Force check of hotkeys state
+        if (AltState()) {
+            int ret = WheelActions(pt, msg, wParam);
+            if (ret == 1) return 1;
+        }
         return CallNextHookEx(NULL, nCode, wParam, lParam);
     }
 
```

Please note that it check the state of the hotkeys only when performing scroll wheel actions, so it shouldn't affect performance too much.

PR is on the way.

**Comment by scx** [comment]
Similar issue: https://github.com/RamonUnch/AltDrag/issues/46

See also: https://github.com/RamonUnch/AltDrag/issues/71

**Comment by RamonUnch** [comment]
Could you make a PR?

**Comment by scx** [comment]
> 
> 
> Could you make a PR?

Done.

Test builds:
 * `MinGW-W64` `i686-8.1.0-win32-sjlj-rt_v6-rev0` - [AltDrag_x86-32.zip](https://github.com/RamonUnch/AltDrag/files/6708595/AltDrag_x86-32.zip)
 * `MinGW-W64` `x86_64-8.1.0-win32-sjlj-rt_v6-rev0` - [AltDrag_x86-64.zip](https://github.com/RamonUnch/AltDrag/files/6708596/AltDrag_x86-64.zip)

**Comment by scx** [comment]
In case someone was affected by this bug and didn't want to wait for **AltDrag** _1.45_, here are the test builds:
 * **`MinGW-W64`** `i686-8.1.0-win32-sjlj-rt_v6-rev0`: 
[AltDrag_1.44+20210624134354.ec07886_x86-32.zip](https://github.com/RamonUnch/AltDrag/files/6711763/AltDrag_1.44%2B20210624134354.ec07886_x86-32.zip)
 * **`MinGW-W64`** `x86_64-8.1.0-win32-sjlj-rt_v6-rev0`: 
[AltDrag_1.44+20210624134354.ec07886_x86-64.zip](https://github.com/RamonUnch/AltDrag/files/6711766/AltDrag_1.44%2B20210624134354.ec07886_x86-64.zip)
 
They are based on ec078869d67764a029a5309d028adc8c20870f5c from Jun 24, 2021.

**Comment by RamonUnch** [comment]
I will keep the issue open until 1.45 is released.

**Comment by RamonUnch** [comment]
1.45 released
