### ISSUE TITLE
Issue with moving dialog windows in recent Windows 10

### ISSUE THREAD

**Issue by joye-ramone** [RamonUnch/AltDrag#76]
I am not exactly sure when this problem appear, but when using Windows 10 version 20h2 moving any dialog window add small padding to window content and change it title padding.
Original window:
![image](https://user-images.githubusercontent.com/5493488/123675729-bd006a80-d84b-11eb-9a45-5a8bad36cde2.png)
After moving with AltDrag:
![image](https://user-images.githubusercontent.com/5493488/123675776-c8539600-d84b-11eb-96c7-5b74fabcd1f6.png)

Visual issue can be resolved by moving window using regular approach.
That is definitely kind of a bug in Windows 10 itself, but I am interesting if that can be workaround in AltDrag

**Comment by RamonUnch** [comment]
Interesting, I had not seen that, the window seems 5px higher and 10px wider...
Probably something can be done about it. I will have a look. for now I have no Win10 computer at hand, but could you test this one. I do not expect any differences but I want to be sure.

[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6728312/AltDrag.zip)

**Comment by joye-ramone** [comment]
Tested - same issue.
Also, just to confirm, same issue appear will all dialogs that I can test (both from windows OS and from other apps)

I use a tool autohotkey for other windows management automation and looks like same problem reproduceable there too and I found this information (not sure if it will be useful but still) https://www.autohotkey.com/boards/viewtopic.php?p=318350#p318350

**Comment by RamonUnch** [comment]
So maybe the solution is to use the SWP_NOSENDCHANGING flag in the SetWindowPos function

[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6729066/AltDrag.zip)

It only should change the MOVE.

**Comment by joye-ramone** [comment]
Tested AltDrag1.45-test2.zip same issue still exists.

**Comment by RamonUnch** [comment]
[AltDrag1.45-test3.zip](https://github.com/RamonUnch/AltDrag/files/6731336/AltDrag1.45-test3.zip)
Well In this case I even specify the SWP_NOSIZE flag...

**Comment by RamonUnch** [comment]
[AltDrag1.45-test4.zip](https://github.com/RamonUnch/AltDrag/files/6731601/AltDrag1.45-test4.zip)
This one fixes snapping and just uses the SWP_NOSIZE flag (as it *should*)

**Comment by RamonUnch** [comment]
I think I saw the same even with Win 8 but not on every dialog.
Did you try to disable the animations under windows using the Performance tabs in the advanced system properties?
Maybe that would help. Just be sure to write the settings you are using before so that you can restore them. But usually I disable all animations.

**Comment by joye-ramone** [comment]
Tested with all disabled features under Performance tab - same result.
I am sure that I was working well in some old windows 10 OS.

Interesting that provided example from autohotkey application works, MoveWindow code has same issue, but SetWindowPos with flag SWP_ASYNCWINDOWPOS (0x4000) move dialogs without this bug.

**Comment by RamonUnch** [comment]
Ok I see I miss-read from the doc the 0x4000 flag.
Try again this onen that works for me...
[AltDrag1.45-test5.zip](https://github.com/RamonUnch/AltDrag/files/6739182/AltDrag1.45-test5.zip)

**Comment by joye-ramone** [comment]
Now it works! Perfect! Will do more testing during day. But from now - all good. Thank you for looking into this.
