### ISSUE TITLE
Transparency: Allow a minimum transparency value to be set

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#8]
Being able to set a minimum value that the transparency can be lowered to would help not losing track of a window accidentally. Currently, the minimum allowed is so low that it's practically entirely invisible. A way to define a minimum value would be appreciated.

```
AltDrag v1.32
Windows 10 20H2
```

**Comment by RamonUnch** [comment]
Good idea, it will be available for next release. Current minimum is 8%

**Comment by RamonUnch** [comment]
Done on AltDrag 1.33
