### ISSUE TITLE
Hotkey + scroll input combination not passed to other applications

### ISSUE THREAD

**Issue by kibihrchak** [RamonUnch/AltDrag#82]
Hi RamonUnch! Thanks a lot for reviving AltDrag and for adding new features 🙂

As for the issue - I have unset mouse scroll handling by AltDrag, and I'm using hotkey (left Win key) + scroll in other applications, namely AutoHotkey (left Win + scroll) and ClickMonitorDDC (Ctrl + left Win + scroll).

This works just fine with 1.43, but starting from version 1.44, input is not passed anymore to those applications when AltDrag is running. That is, when holding eg. left Win + scrolling, input is not received by AHK. This happens regardless of the selected hotkey (at least, I saw the same behavior using left Alt as a hotkey) and version (1.45 behaves the same way).

Also, hotkey combinations which does not involve mouse scroll (eg. Ctrl + left Win + x) continue to work with no issues and are caught by other applications.

I'm wondering, has something changed in scroll wheel handling between the versions, and is the change reversible?

As for the system details, OS on which I'm running is Win 10 Pro, 21H1. Write if you need some more troubleshooting details.

**Comment by RamonUnch** [comment]
Yes, the code changed, between version, I will invistigate your problem, should not be hard to fix.

**Comment by RamonUnch** [comment]
Fixed, Try this one:
[AltDrag.zip](https://github.com/RamonUnch/AltDrag/files/6836792/AltDrag.zip)

**Comment by kibihrchak** [comment]
Thanks a lot! Can confirm that it behaves the same way as 1.43 version. Closing.
