### ISSUE TITLE
Feature Request: Add Mouse Scroll Down Action and new Action

### ISSUE THREAD

**Issue by fekfoq259** [RamonUnch/AltDrag#84]
Mouse actions's "Volume" can recognize "scroll whell up" and "scroll whell down"
Maybe some people wnat binding different with :
Hotkeys + scroll whell up
Hotkeys + scroll whell down

**Comment by RamonUnch** [comment]
What is the difference with the Alt+Tab scroll action?
I am not sure I understand your request...

**Comment by fekfoq259** [comment]
> What is the difference with the Alt+Tab scroll action?
> I am not sure I understand your request...
Mouse actions's "Volume" can recognize "scroll whell up" and "scroll whell down"
But I want do different action with "Alt + scroll whell up" and "Alt + scroll whell down"

**Comment by fekfoq259** [comment]
> What is the difference with the Alt+Tab scroll action?
> I am not sure I understand your request...

You are right. It Alt + Tab function. Thanks.
