### ISSUE TITLE
Bug: `FullWin=0` is slow and not performant

### ISSUE THREAD

**Issue by redactedscribe** [RamonUnch/AltDrag#9]
The `.ini` claims that setting `FullWin` to `0` should be more performant, yet the rectangle it draws is drawn and updates much slower than when the full window is drawn normally (`FullWin=1`).
```
AltDrag v1.32
Windows 10 20H2
```

**Comment by RamonUnch** [comment]
This is normal, it is a Windows bug that makes GDI drawing a million time slower when desktop composition is enabled.
This option is for the moment reserved for Windows 7 and below without desktop composition enabled.

**Comment by redactedscribe** [comment]
Good idea. Thanks.
